Repository vanjarosoftware/Vanjaro.Platform, pull requests merged in 2020-11, with the labels that each got.

#296 Theme.css not compiling on DOUpgradable call
  DesktopModules/Vanjaro/Core/Library/Managers/SettingManager.cs
  DesktopModules/Vanjaro/Core/Library/Managers/ThemeManager.cs
  DesktopModules/Vanjaro/UXManager/Extensions/Menu/Theme/Controllers/SettingController.cs
  DesktopModules/Vanjaro/UXManager/Extensions/Menu/ThemeBuilder/Controllers/SettingsController.cs
Labels: Area: Backend, Area: Frontend, Bug

#290 Vanajro URL Library directory and service route rename with vjURL
  DesktopModules/Vanjaro/URL/web.Debug.config
  DesktopModules/Vanjaro/URL/web.Release.config
  DesktopModules/Vanjaro/URL/web.config
  DesktopModules/Vanjaro/URLManager/App.config
  DesktopModules/Vanjaro/URLManager/Common/Cache.cs
  DesktopModules/Vanjaro/URLManager/Common/IPropertyChanged.cs
  DesktopModules/Vanjaro/URLManager/Controllers/ServiceRouteMapper.cs
  DesktopModules/Vanjaro/URLManager/Controllers/UIController.cs
  DesktopModules/Vanjaro/URLManager/Controllers/UrlController.cs
  DesktopModules/Vanjaro/URLManager/Data/Entities/URLEntity.cs
  DesktopModules/Vanjaro/URLManager/Data/Scripts/CommonScript.cs
  DesktopModules/Vanjaro/URLManager/Factories/AppFactory.cs
  DesktopModules/Vanjaro/URLManager/Factories/URLFactory.cs
  DesktopModules/Vanjaro/URLManager/Install/URL.01.00.00.SqlDataProvider
  DesktopModules/Vanjaro/URLManager/Install/URL.xml
  DesktopModules/Vanjaro/URLManager/Install/Uninstall.URL.SqlDataProvider
  DesktopModules/Vanjaro/URLManager/Managers/IURLService.cs
  DesktopModules/Vanjaro/URLManager/Managers/URLManager.cs
  DesktopModules/Vanjaro/URLManager/Models/Generated/Database.cs
  DesktopModules/Vanjaro/URLManager/Models/Generated/Database.tt
  DesktopModules/Vanjaro/URLManager/Models/Generated/PetaPoco.Core.ttinclude
  DesktopModules/Vanjaro/URLManager/Models/Generated/PetaPoco.Generator.ttinclude
  DesktopModules/Vanjaro/URLManager/Models/PetaPoco.cs
  DesktopModules/Vanjaro/URLManager/Models/URLLibraryRepo.cs
  DesktopModules/Vanjaro/URLManager/Properties/AssemblyInfo.cs
  DesktopModules/Vanjaro/URLManager/Providers/URLProvider.cs
  DesktopModules/Vanjaro/URLManager/Resources.txt
  DesktopModules/Vanjaro/URLManager/Utilities/StringExtension.cs
  DesktopModules/Vanjaro/URLManager/Vanjaro.URL.csproj
  DesktopModules/Vanjaro/URLManager/Views/App_LocalResources/Shared.resx
  DesktopModules/Vanjaro/URLManager/Views/Settings.ascx
  DesktopModules/Vanjaro/URLManager/Views/Settings.ascx.cs
  DesktopModules/Vanjaro/URLManager/Views/Settings.ascx.designer.cs
  DesktopModules/Vanjaro/URLManager/Views/Url/App_LocalResources/Manage.resx
  DesktopModules/Vanjaro/URLManager/Views/Url/Manage.html
  DesktopModules/Vanjaro/URLManager/Views/Url/Manage.js
  DesktopModules/Vanjaro/URLManager/Views/View.ascx
  DesktopModules/Vanjaro/URLManager/Views/View.ascx.cs
  DesktopModules/Vanjaro/URLManager/Views/View.ascx.designer.cs
  DesktopModules/Vanjaro/URLManager/url-resources.zip
  Vanjaro Platform.sln
Labels: Area: Backend, Bug, Priority: Medium

#313 renamed url to url library
  DesktopModules/Vanjaro/Core/Library/00.05.03.txt
  DesktopModules/Vanjaro/Core/Library/Install/Core.01.00.00.SqlDataProvider
  DesktopModules/Vanjaro/Core/Library/Install/Core.01.00.03.SqlDataProvider
  DesktopModules/Vanjaro/Core/Library/PackageList.txt
  DesktopModules/Vanjaro/Core/Library/Vanjaro.Core.csproj
  DesktopModules/Vanjaro/Core/Library/Vanjaro.dnn
  DesktopModules/Vanjaro/Core/Library/VanjaroDistrubtion.dnn
Labels: Area: Backend, Bug, Priority: Medium, Release: Minor
