Repository vanjarosoftware/Vanjaro.Platform, pull requests merged in 2021-02, with the labels that each got.

#694 Search Inline Work;Page displays nothing
  DesktopModules/Vanjaro/UXManager/Extensions/Block/SearchInput/Controllers/SearchController.cs
  DesktopModules/Vanjaro/UXManager/Extensions/Block/SearchInput/Managers/SearchInputManager.cs
  DesktopModules/Vanjaro/UXManager/Extensions/Block/SearchResult/Managers/SearchResultManager.cs
Labels: Area: Backend, Bug, Priority: Medium

#697 Signup is broken after making registration public. No Redirect
  DesktopModules/Vanjaro/UXManager/Extensions/Block/Register/Managers/RegisterManager.cs
Labels: Area: Backend, Bug, Priority: Medium

#732 Added Type block in Library URL
  DesktopModules/Vanjaro/UXManager/Library/Base.ascx.cs
Labels: Area: Backend, Bug

#746 Uploaded Block on Azure folder not import on page from library #743
  DesktopModules/Vanjaro/UXManager/Library/Controllers/BlockController.cs
  DesktopModules/Vanjaro/UXManager/Library/Resources/Scripts/GrapesJsManagers/editor.js
Labels: Area: Backend, Bug, Priority: Medium

#773 dropdown menu implemented
  DesktopModules/Vanjaro/UXManager/Extensions/Menu/Theme/Resources/Stylesheets/app.css
  DesktopModules/Vanjaro/UXManager/Extensions/Menu/Theme/Views/App_LocalResources/Shared.resx
  DesktopModules/Vanjaro/UXManager/Extensions/Menu/Theme/Views/Setting/Setting.html
Labels: Area: Frontend, Priority: Low, Release: Minor

#786 Disable Language
  DesktopModules/Vanjaro/UXManager/Extensions/Menu/Languages/Controllers/LanguagesController.cs
  DesktopModules/Vanjaro/UXManager/Extensions/Menu/Languages/Views/Setting/Languages.js
Labels: Area: Backend, Bug

#783 Search Results page after vanjaro upgrade
  DesktopModules/Vanjaro/Core/Library/Managers/SettingManager.cs
Labels: Area: Backend, Bug

#837 Remove "id" attribute from Language block on Preview
  Portals/_default/Skins/Vanjaro/Base.ascx.cs
Labels: Area: Backend, Area: Frontend
