Repository vanjarosoftware/Vanjaro.Platform, pull requests merged in 2021-03, with the labels that each got.

#865 Failed to instantiate module Pages due to: RangeError: Maximum call stack size exceeded
  DesktopModules/Vanjaro/UXManager/Extensions/Menu/Domain/Factories/AppFactory.cs
  DesktopModules/Vanjaro/UXManager/Extensions/Menu/EmailServiceProvider/Factories/AppFactory.cs
  DesktopModules/Vanjaro/UXManager/Extensions/Menu/Help/Factories/AppFactory.cs
  DesktopModules/Vanjaro/UXManager/Extensions/Menu/LogoAndTitle/Factories/AppFactory.cs
  DesktopModules/Vanjaro/UXManager/Extensions/Menu/MemberProfile/Factories/AppFactory.cs
  DesktopModules/Vanjaro/UXManager/Extensions/Menu/Pages/Factories/AppFactory.cs
  DesktopModules/Vanjaro/UXManager/Extensions/Menu/Privacy/Factories/AppFactory.cs
  DesktopModules/Vanjaro/UXManager/Extensions/Menu/Roles/Factories/AppFactory.cs
  DesktopModules/Vanjaro/UXManager/Extensions/Menu/SEO/Factories/AppFactory.cs
  DesktopModules/Vanjaro/UXManager/Extensions/Menu/Security/Factories/AppFactory.cs
  DesktopModules/Vanjaro/UXManager/Extensions/Menu/Theme/Factories/AppFactory.cs
  DesktopModules/Vanjaro/UXManager/Extensions/Menu/ThemeBuilder/Factories/AppFactory.cs
  DesktopModules/Vanjaro/UXManager/Extensions/Menu/Users/Factories/AppFactory.cs
  DesktopModules/Vanjaro/UXManager/Extensions/Toolbar/DeviceMode/Factories/AppFactory.cs
  DesktopModules/Vanjaro/UXManager/Extensions/Toolbar/Fullscreen/Factories/AppFactory.cs
  DesktopModules/Vanjaro/UXManager/Extensions/Toolbar/Language/Factories/AppFactory.cs
  DesktopModules/Vanjaro/UXManager/Extensions/Toolbar/Navigator/Factories/AppFactory.cs
  DesktopModules/Vanjaro/UXManager/Extensions/Toolbar/PageSetting/Factories/AppFactory.cs
  DesktopModules/Vanjaro/UXManager/Extensions/Toolbar/Preview/Factories/AppFactory.cs
  DesktopModules/Vanjaro/UXManager/Extensions/Toolbar/VersionManagement/Factories/AppFactory.cs
  DesktopModules/Vanjaro/UXManager/Extensions/Toolbar/ViewLayout/Factories/AppFactory.cs
Labels: Bug

#868 Add scroll at premium app assignment
  DesktopModules/Vanjaro/UXManager/Extensions/Menu/Extensions/Resources/Stylesheets/app.css
Labels: Area: Frontend, Priority: Low

#904 Manage users ui broken in roles #882
  DesktopModules/Vanjaro/UXManager/Extensions/Menu/Roles/Views/Setting/AddUser.html
Labels: Area: Frontend, Priority: High, Release: Minor

#906 Sub folders are not visible in parent dropdown
  DesktopModules/Vanjaro/UXManager/Extensions/Menu/Pages/Controllers/PagesController.cs
  DesktopModules/Vanjaro/UXManager/Library/Managers/PageManager.cs
Labels: Area: Backend, Bug, Priority: High, Release: Major

#900 Missing parent dropdown while creating redirect page #893
  DesktopModules/Vanjaro/UXManager/Extensions/Menu/Pages/Views/Setting/Detail.html
Labels: Bug, Priority: High, Release: Major

#905 Show error message instead of showing loading icon in sign in form
  DesktopModules/Vanjaro/Core/Library/App_LocalResources/Shared.resx
  DesktopModules/Vanjaro/UXManager/Extensions/Block/Login/Controllers/LoginController.cs
  DesktopModules/Vanjaro/UXManager/Extensions/Block/Login/Managers/LoginManager.cs
  DesktopModules/Vanjaro/UXManager/Extensions/Block/Login/Resources/Scripts/Login.js
Labels: Area: Frontend, Enhancement, Priority: Medium

#924 #886 improve sign up and my account
  DesktopModules/Vanjaro/Core/Library/Themes/Basic/App_LocalResources/Shared.resx
  DesktopModules/Vanjaro/Core/Library/Themes/Basic/blocks/Register Link/Templates/Default.cshtml
  DesktopModules/Vanjaro/Core/Library/Themes/Basic/blocks/Register Link/register link.html
  DesktopModules/Vanjaro/Core/Library/Themes/Basic/templates/pages/Default.json
  DesktopModules/Vanjaro/Core/Library/Themes/Basic/templates/pages/Home.json
  DesktopModules/Vanjaro/Core/Library/Themes/Basic/templates/website/Default.json
  DesktopModules/Vanjaro/Core/Library/Themes/Basic/templates/website/Home.json
  DesktopModules/Vanjaro/Core/Library/Themes/Basic/templates/website/NotFoundPage.json
  DesktopModules/Vanjaro/Core/Library/Themes/Basic/templates/website/Privacy.json
  DesktopModules/Vanjaro/Core/Library/Themes/Basic/templates/website/Profile.json
  DesktopModules/Vanjaro/Core/Library/Themes/Basic/templates/website/SearchResults.json
  DesktopModules/Vanjaro/Core/Library/Themes/Basic/templates/website/Terms.json
  DesktopModules/Vanjaro/Core/Library/Themes/Basic/theme.editor.json
  DesktopModules/Vanjaro/UXManager/Extensions/Block/RegisterLink/Controllers/LoginLinkController.cs
  DesktopModules/Vanjaro/UXManager/Extensions/Block/RegisterLink/Controllers/RegisterLinkController.cs
  DesktopModules/Vanjaro/UXManager/Extensions/Block/RegisterLink/Entities/LoginLink.cs
  DesktopModules/Vanjaro/UXManager/Extensions/Block/RegisterLink/Entities/RegisterLink.cs
  DesktopModules/Vanjaro/UXManager/Extensions/Block/RegisterLink/Managers/LoginLinkManager.cs
  DesktopModules/Vanjaro/UXManager/Extensions/Block/RegisterLink/RegisterLink.cs
  DesktopModules/Vanjaro/UXManager/Extensions/Block/RegisterLink/RegisterLink.csproj
  DesktopModules/Vanjaro/UXManager/Extensions/Block/RegisterLink/Views/App_LocalResources/Shared.resx
  DesktopModules/Vanjaro/UXManager/Extensions/Block/RegisterLink/Views/Setting/App_LocalResources/RegisterLink.resx
  DesktopModules/Vanjaro/UXManager/Extensions/Block/RegisterLink/Views/Setting/RegisterLink.html
  DesktopModules/Vanjaro/UXManager/Extensions/Block/RegisterLink/Views/Setting/RegisterLink.js
  Vanjaro Platform.sln
Labels: Area: Backend, Area: Frontend, Enhancement, Priority: Medium, Release: Minor

#930 Logo & Site Icon Issues
  DesktopModules/Vanjaro/Common/Frameworks/AngularJS/Plugins/mnCommonService/mnCommonService.css
  DesktopModules/Vanjaro/UXManager/Extensions/Menu/LogoAndTitle/Resources/Stylesheets/app.css
  DesktopModules/Vanjaro/UXManager/Extensions/Menu/LogoAndTitle/Views/Setting/Setting.html
Labels: Area: Backend, Area: Frontend, Release: Minor

#934 Rename page then hit on page settings
  DesktopModules/Vanjaro/UXManager/Extensions/Menu/Pages/Views/Setting/Detail.js
Labels: Area: Backend, Bug, Priority: Medium

#959 Sub pages are not visible in parent dropdown
  DesktopModules/Vanjaro/UXManager/Library/Managers/PageManager.cs
Labels: Area: Backend, Bug, Priority: High, Release: Major

#967 Nested pages should not auto expand
  DesktopModules/Vanjaro/UXManager/Extensions/Menu/Pages/Controllers/PagesController.cs
  DesktopModules/Vanjaro/UXManager/Extensions/Menu/Pages/Resources/UIEngine/AngularBootstrap/Elements/TreeView.htm
Labels: Area: Backend, Area: Frontend, Bug, Enhancement

#975 Installed Dnn modules like 2sxc don't appear till the page is refreshed
  DesktopModules/Vanjaro/UXManager/Extensions/Menu/Extensions/Views/Settings/DeleteExtension.js
  DesktopModules/Vanjaro/UXManager/Extensions/Menu/Extensions/Views/Settings/EditExtension.js
  DesktopModules/Vanjaro/UXManager/Extensions/Menu/Extensions/Views/Settings/InstallExtension.js
  DesktopModules/Vanjaro/UXManager/Library/Resources/Scripts/GrapesJsManagers/desktopmodulesApps.js
Labels: Area: Backend, Bug, Priority: High, Release: Major

#992 Upgrade DNN to 9.9.0
  DesktopModules/Vanjaro/Core/Library/Managers/SettingManager.cs
  DesktopModules/Vanjaro/Core/Library/Packager/Packager.bat
  DesktopModules/Vanjaro/Core/Library/Vanjaro.dnn
  DesktopModules/Vanjaro/Core/Library/VanjaroDistribution.dnn
  DesktopModules/Vanjaro/UXManager/Extensions/Menu/Sites/Managers/SitesManager.cs
  DesktopModules/Vanjaro/UXManager/Library/Vanjaro.UX.csproj
Labels: Enhancement
