Repository vanjarosoftware/Vanjaro.Platform, pull requests merged in 2021-12, with the labels that each got.

#1956 Created Interface IPortalDelerte
  DesktopModules/Vanjaro/Core/Library/Entities/Interface/IPortalDelete.cs
  DesktopModules/Vanjaro/Core/Library/Factories/CacheFactory.cs
  DesktopModules/Vanjaro/Core/Library/Managers/SiteManager.cs
  DesktopModules/Vanjaro/Core/Library/Vanjaro.Core.csproj
  DesktopModules/Vanjaro/UXManager/Extensions/Menu/Sites/Managers/SitesManager.cs
Labels: Enhancement, Release: Minor, Priority: Medium, Area: Backend

#1961 Always showing localization key in url manage render
  DesktopModules/Vanjaro/URLManager/Views/View.ascx.cs
Labels: Bug, Release: Minor, Priority: Medium, Area: Backend

#1989 Fixed Re Captcha issues
  DesktopModules/Vanjaro/Core/Library/Services/Captcha/Captcha.cs
  DesktopModules/Vanjaro/Core/Library/Themes/Basic/blocks/Login/Templates/Default.cshtml
  DesktopModules/Vanjaro/Core/Library/Themes/Basic/blocks/Register/Templates/Default.cshtml
  DesktopModules/Vanjaro/UXManager/Extensions/Block/Login/Controllers/LoginController.cs
  DesktopModules/Vanjaro/UXManager/Extensions/Block/Register/Controllers/RegisterController.cs
  Portals/_default/Skins/Vanjaro/Resources/js/skin.js
Labels: Bug, Area: Backend

#1997 Added LogType Column into MailQueue_Log
  DesktopModules/Vanjaro/Common/Components/Scheduler.cs
  DesktopModules/Vanjaro/Common/Install/Common.01.03.00.SqlDataProvider
  DesktopModules/Vanjaro/Common/Models/Generated/Database.cs
  DesktopModules/Vanjaro/Common/Vanjaro.Common.csproj
  DesktopModules/Vanjaro/Core/Library/Properties/GlobalAssemblyInfo.cs
  DesktopModules/Vanjaro/Core/Library/Vanjaro.dnn
  DesktopModules/Vanjaro/Core/Library/VanjaroDistribution.dnn
Labels: Enhancement, Area: Backend

#2000 #1999 Notification add position along with width
  DesktopModules/Vanjaro/Core/Extensions/Notification/Notification/Managers/TasksManager.cs
  DesktopModules/Vanjaro/Core/Library/Components/NotificationItem.cs
Labels: Enhancement, Area: Backend
