Repository vanjarosoftware/Vanjaro.Platform, pull requests merged in 2021-09, with the labels that each got.

#1738 Profile link not hide even if setting disabled
  DesktopModules/Vanjaro/Core/Library/Themes/Basic/blocks/Register Link/Templates/Default.cshtml
Labels: Bug, Priority: Medium, Area: Backend, .NET

#1739 Vanjaro DNN Version Upgrade to 9.10.1
  DesktopModules/Vanjaro/Core/Extensions/Notification/Notification/Notification.csproj
  DesktopModules/Vanjaro/Core/Extensions/Workflow/Review/Review.csproj
  DesktopModules/Vanjaro/Core/Library/Packager/Packager.bat
  DesktopModules/Vanjaro/Core/Providers/Authentication/Authentication.csproj
  DesktopModules/Vanjaro/UXManager/Extensions/Apps/About/About.csproj
  DesktopModules/Vanjaro/UXManager/Extensions/Apps/Icon/Icon.csproj
  DesktopModules/Vanjaro/UXManager/Extensions/Apps/Link/Link.csproj
  DesktopModules/Vanjaro/UXManager/Extensions/Apps/ModuleSettings/ModuleSettings.csproj
  DesktopModules/Vanjaro/UXManager/Extensions/Apps/SectionSettings/SectionSettings.csproj
  DesktopModules/Vanjaro/UXManager/Extensions/Apps/Video/Video.csproj
  DesktopModules/Vanjaro/UXManager/Extensions/Block/Language/BlockLanguage.csproj
  DesktopModules/Vanjaro/UXManager/Extensions/Block/Menu/Menu.csproj
  DesktopModules/Vanjaro/UXManager/Extensions/Block/SearchInput/SearchInput.csproj
  DesktopModules/Vanjaro/UXManager/Extensions/Menu/Domain/Domain.csproj
  DesktopModules/Vanjaro/UXManager/Extensions/Menu/Extensions/Extensions.csproj
  DesktopModules/Vanjaro/UXManager/Extensions/Menu/GoogleReCaptcha/GoogleReCaptcha.csproj
  DesktopModules/Vanjaro/UXManager/Extensions/Menu/LogsSettings/LogsSettings.csproj
  DesktopModules/Vanjaro/UXManager/Extensions/Menu/MemberProfile/MemberProfile.csproj
  DesktopModules/Vanjaro/UXManager/Extensions/Menu/Memberships/Memberships.csproj
  DesktopModules/Vanjaro/UXManager/Extensions/Menu/SEO/SEO.csproj
  DesktopModules/Vanjaro/UXManager/Extensions/Menu/Security/Security.csproj
  DesktopModules/Vanjaro/UXManager/Extensions/Menu/SiteGroups/SiteGroups.csproj
  DesktopModules/Vanjaro/UXManager/Extensions/Menu/Theme/Theme.csproj
  DesktopModules/Vanjaro/UXManager/Extensions/Menu/ThemeBuilder/ThemeBuilder.csproj
  DesktopModules/Vanjaro/UXManager/Extensions/Menu/Users/Users.csproj
  DesktopModules/Vanjaro/UXManager/Extensions/Menu/Workflow/Workflow.csproj
  DesktopModules/Vanjaro/UXManager/Extensions/Toolbar/DeviceMode/DeviceMode.csproj
  DesktopModules/Vanjaro/UXManager/Extensions/Toolbar/Fullscreen/Fullscreen.csproj
  DesktopModules/Vanjaro/UXManager/Extensions/Toolbar/Language/Language.csproj
  DesktopModules/Vanjaro/UXManager/Extensions/Toolbar/Navigator/Navigator.csproj
  DesktopModules/Vanjaro/UXManager/Extensions/Toolbar/PageSetting/PageSetting.csproj
  DesktopModules/Vanjaro/UXManager/Extensions/Toolbar/Preview/Preview.csproj
  DesktopModules/Vanjaro/UXManager/Extensions/Toolbar/ViewLayout/ViewLayout.csproj
  DesktopModules/Vanjaro/UXManager/Library/Vanjaro.UX.csproj
Labels: Enhancement, Release: Minor, Priority: Medium, Area: Backend

#1753 Vanjaro for DNN - App removing from page after reloading the page without publish
  DesktopModules/Vanjaro/UXManager/Extensions/Migrate/Vanjaro/Vanjaro.html
Labels: Bug, Priority: High, Area: Backend

#1764 Replace old Vanjaro logo
  DesktopModules/Vanjaro/UXManager/Extensions/Migrate/Vanjaro/Vanjaro.html
  DesktopModules/Vanjaro/UXManager/Extensions/Migrate/Vanjaro/images/VJ-logo.png
Labels: Enhancement, Priority: Low

#1761 View slugs history not binding
  DesktopModules/Vanjaro/Common/Frameworks/AngularJS/Plugins/mnCommonService/mnCommonService.js
  DesktopModules/Vanjaro/Common/Frameworks/AngularJS/Plugins/mnCommonService/mnCommonService.min.js
Labels: Bug, Applies to: Platform Only

#1760 Remove not using Login Link project
  DesktopModules/Vanjaro/UXManager/Extensions/Block/LoginLink/Components/Constants.cs
  DesktopModules/Vanjaro/UXManager/Extensions/Block/LoginLink/Controllers/LoginLinkController.cs
  DesktopModules/Vanjaro/UXManager/Extensions/Block/LoginLink/Controllers/ServiceRouteMapper.cs
  DesktopModules/Vanjaro/UXManager/Extensions/Block/LoginLink/Controllers/UIController.cs
  DesktopModules/Vanjaro/UXManager/Extensions/Block/LoginLink/Entities/LoginLink.cs
  DesktopModules/Vanjaro/UXManager/Extensions/Block/LoginLink/ExtensionInfo.cs
  DesktopModules/Vanjaro/UXManager/Extensions/Block/LoginLink/Factories/AppFactory.cs
  DesktopModules/Vanjaro/UXManager/Extensions/Block/LoginLink/LoginLink.cs
  DesktopModules/Vanjaro/UXManager/Extensions/Block/LoginLink/LoginLink.csproj
  DesktopModules/Vanjaro/UXManager/Extensions/Block/LoginLink/Managers/LoginLinkManager.cs
  DesktopModules/Vanjaro/UXManager/Extensions/Block/LoginLink/Properties/AssemblyInfo.cs
  DesktopModules/Vanjaro/UXManager/Extensions/Block/LoginLink/Resources.txt
  DesktopModules/Vanjaro/UXManager/Extensions/Block/LoginLink/Views/App_LocalResources/Shared.resx
  DesktopModules/Vanjaro/UXManager/Extensions/Block/LoginLink/Views/Setting/App_LocalResources/Login.resx
  DesktopModules/Vanjaro/UXManager/Extensions/Block/LoginLink/Views/Setting/LoginLink.html
  DesktopModules/Vanjaro/UXManager/Extensions/Block/LoginLink/Views/Setting/LoginLink.js
  DesktopModules/Vanjaro/UXManager/Extensions/Block/LoginLink/web.Debug.config
  DesktopModules/Vanjaro/UXManager/Extensions/Block/LoginLink/web.Release.config
  DesktopModules/Vanjaro/UXManager/Extensions/Block/LoginLink/web.config
Labels: Enhancement, Applies to: Platform Only

#1768 Added Next and previous buttons in pagination
  DesktopModules/Vanjaro/Common/Frameworks/AngularJS/Plugins/SmartTable/smart-table.js
  DesktopModules/Vanjaro/Common/Frameworks/AngularJS/Plugins/SmartTable/smart-table.min.js
Labels: Enhancement, Release: Minor, Priority: Medium, Area: Backend

#1773 Unable to Get Vanjaro to Work with DNN 9.9.1
  DesktopModules/Vanjaro/UXManager/Extensions/Migrate/Components/HttpModule.cs
Labels: Bug, Area: Backend

#1784 Update platform version to 1.2.0
  DesktopModules/Vanjaro/Core/Library/Install/Core.01.02.00.SqlDataProvider
  DesktopModules/Vanjaro/Core/Library/Properties/GlobalAssemblyInfo.cs
  DesktopModules/Vanjaro/Core/Library/Vanjaro.Core.csproj
  DesktopModules/Vanjaro/Core/Library/Vanjaro.dnn
  DesktopModules/Vanjaro/Core/Library/VanjaroDistribution.dnn
Labels: Bug, Release: Major, Priority: Medium, Area: Backend

#1786 Fixed: Unable to copy page permisson while copy the page.
  DesktopModules/Vanjaro/UXManager/Extensions/Menu/Pages/Managers/PagesManager.cs
Labels: Bug, Release: Minor, Priority: Medium, Area: Backend, .NET

#1788 Added search in Sites grid
  DesktopModules/Vanjaro/UXManager/Extensions/Menu/Sites/Controllers/SitesController.cs
  DesktopModules/Vanjaro/UXManager/Extensions/Menu/Sites/Views/Setting/App_LocalResources/Sites.resx
  DesktopModules/Vanjaro/UXManager/Extensions/Menu/Sites/Views/Setting/Sites.html
  DesktopModules/Vanjaro/UXManager/Extensions/Menu/Sites/Views/Setting/Sites.js
Labels: Enhancement, Release: Minor, Priority: Medium, Area: Backend, .NET

#1791 Required profile fields ui change
  DesktopModules/Vanjaro/UXManager/Extensions/Menu/Users/Controllers/UpdateProfileController.cs
  DesktopModules/Vanjaro/UXManager/Extensions/Menu/Users/Controllers/UserController.cs
  DesktopModules/Vanjaro/UXManager/Extensions/Menu/Users/Views/Setting/UpdateProfile.html
Labels: Area: Frontend

#1794 Root menu does not show as selected when its child page is selected
  DesktopModules/Vanjaro/Core/Library/Themes/Basic/blocks/Menu/Templates/Default.cshtml
Labels: Bug, Release: Minor, Priority: Medium, Area: Backend, .NET

#1797 release log updated
  DesktopModules/Vanjaro/Core/Library/Release.txt
  DesktopModules/Vanjaro/UXManager/Library/Release.txt
Labels: Area: Backend
