Repository vanjarosoftware/Vanjaro.Platform, pull requests merged in 2021-01, with the labels that each got.

#600 #596 google analytics tracking issue with release build production measurement id not using
  DesktopModules/Vanjaro/Core/Library/Packager/Packager.bat
  DesktopModules/Vanjaro/Core/Library/Services/Analytics/Analytics.cs
  DesktopModules/Vanjaro/Core/Library/Vanjaro.Core.csproj
  DesktopModules/Vanjaro/Core/Library/Vanjaro.dnn
  DesktopModules/Vanjaro/Core/Library/VanjaroDistribution.dnn
Labels: Area: Backend, Bug, Priority: High

#601 Issue with default created page edit permission and profile page not showing in User folder
  DesktopModules/Vanjaro/Core/Library/Managers/SettingManager.cs
  DesktopModules/Vanjaro/Core/Library/Packager/Vanjaro/Default Website.template
Labels: Area: Backend, Bug, Priority: High

#613 Commented the Guided Tour Calling
  Portals/_default/Skins/Vanjaro/Base.ascx.cs
Labels: Area: Backend, Enhancement, Priority: High, Release: Major

#645 Migrate to vanjaro break with changed cookies name
  Portals/_default/Skins/Vanjaro/Base.ascx.cs
Labels: Area: Backend
