Repository vanjarosoftware/Vanjaro.Platform, pull requests merged in 2021-08, with the labels that each got.

#1573 Product SKU refactor
  DesktopModules/Vanjaro/Common/Components/Product.cs
  DesktopModules/Vanjaro/Common/Factories/NotificationFactory.cs
  DesktopModules/Vanjaro/Common/Vanjaro.Common.csproj
  DesktopModules/Vanjaro/Core/Library/Vanjaro.Core.csproj
  DesktopModules/Vanjaro/UXManager/Extensions/Apps/About/Controllers/AboutController.cs
  DesktopModules/Vanjaro/UXManager/Library/Base.ascx.cs
Labels: Area: Backend, Enhancement

#1656 Unable to edit content in edit mode
  DesktopModules/Vanjaro/UXManager/Library/Resources/Scripts/GrapesJsManagers/editor.js
Labels: Bug, Area: Backend, javascript

#1660 Make third party module link color white in edit mode
  DesktopModules/Vanjaro/UXManager/Library/Resources/Scripts/GrapesJsManagers/css/uxmanager.css
Labels: Bug, Release: Major, Area: Frontend
