Repository vanjarosoftware/Vanjaro.Platform, pull requests merged in 2021-11, with the labels that each got.

#1926 #1925 error importing template or creating site
  DesktopModules/Vanjaro/Core/Library/Factories/PageFactory.cs
  DesktopModules/Vanjaro/Core/Library/Managers/PageManager.cs
Labels: Bug, Area: Backend

#1931 Fixed Image does not change
  DesktopModules/Vanjaro/UXManager/Library/Resources/Scripts/GrapesJsManagers/editor.js
Labels: Bug, Release: Minor, Priority: Low, Area: Backend

#1938 Fixed issue
  DesktopModules/Vanjaro/UXManager/Library/Resources/Scripts/GrapesJsManagers/editor.js
Labels: Bug, Priority: Medium, Area: Frontend
