Repository vanjarosoftware/Vanjaro.Platform, pull requests merged in 2022-03, with the labels that each got.

#2122 Clear client cache on app install form store
  DesktopModules/Vanjaro/UXManager/Extensions/Menu/Extensions/Controllers/InstallPackageController.cs
Labels: Bug, Release: Minor, Priority: Low, Area: Backend

#2128 Notification dismiss is not clearing cache immediately
  DesktopModules/Vanjaro/Core/Extensions/Notification/Notification/Controllers/NotificationController.cs
  DesktopModules/Vanjaro/Core/Extensions/Notification/Notification/Views/Notification/Notifications.js
  DesktopModules/Vanjaro/Core/Library/Managers/NotificationManager.cs
Labels: Bug, Priority: Medium

#2120 Change Default Messages
  DesktopModules/Vanjaro/Core/Library/Install/Core.01.03.01.SqlDataProvider
  DesktopModules/Vanjaro/Core/Library/Managers/SettingManager.cs
  DesktopModules/Vanjaro/Core/Library/Packager/Vanjaro/DotNetNuke.install.config.resources
  DesktopModules/Vanjaro/Core/Library/Vanjaro.Core.csproj
  DesktopModules/Vanjaro/Core/Library/Vanjaro.dnn
  DesktopModules/Vanjaro/Core/Library/VanjaroDistribution.dnn
Labels: Enhancement, Priority: Low, Area: Backend

#2151 Dont send global block html on save call if its locked
  DesktopModules/Vanjaro/Core/Library/Managers/PageManager.cs
  DesktopModules/Vanjaro/UXManager/Library/Resources/Scripts/GrapesJsManagers/editor.js
Labels: Enhancement, Release: Minor, Priority: Low, Area: Backend

#2153 Improved Image Optimization Funtion
  DesktopModules/Vanjaro/UXManager/Library/Resources/Scripts/GrapesJsManagers/editor.js
Labels: Enhancement, Release: Minor, Priority: Medium, Area: Frontend
