Repository vanjarosoftware/Vanjaro.Platform, pull requests merged in 2022-01, with the labels that each got.

#2004 After Sign Up user not redirecting to set page
  DesktopModules/Vanjaro/UXManager/Extensions/Block/Register/Controllers/RegisterController.cs
Labels: Bug, Area: Backend

#2012 image editor error
  DesktopModules/Vanjaro/UXManager/Library/Resources/Scripts/Blocks/index.js
Labels: Bug, Release: Minor, Priority: Low, Area: Backend

#2032 Can't select Folder-type page within Menu settings
  DesktopModules/Vanjaro/UXManager/Extensions/Block/Menu/Controllers/MenuController.cs
Labels: Bug, Area: Backend

#2049 Fixed Button set to DNN page link doesn't work and page data length check
  DesktopModules/Vanjaro/UXManager/Library/Base.ascx.cs
  DesktopModules/Vanjaro/UXManager/Library/Controllers/PageController.cs
  DesktopModules/Vanjaro/UXManager/Library/Resources/Scripts/Blocks/traits.js
  DesktopModules/Vanjaro/UXManager/Library/Resources/Scripts/GrapesJsManagers/editor.js
  DesktopModules/Vanjaro/UXManager/Library/Resources/StyleSheets/app.css
Labels: Bug, Release: Minor, Priority: Low, Area: Backend

#2055 jQueryUI on page with edit permission or admin
  DesktopModules/Vanjaro/Core/Library/Managers/PageManager.cs
  Portals/_default/Skins/Vanjaro/Base.ascx.cs
Labels: Bug, Release: Minor, Priority: Low, Area: Backend

#2060 changed dataLength to 5mb
  DesktopModules/Vanjaro/UXManager/Library/Controllers/PageController.cs
  DesktopModules/Vanjaro/UXManager/Library/Resources/Scripts/GrapesJsManagers/editor.js
Labels: ignore for release

#2067 #2066 Return URL doesn't work with Sign Up block
  DesktopModules/Vanjaro/UXManager/Extensions/Block/Register/Resources/Scripts/Register.js
Labels: Bug, Area: Backend

#2069 Updated vanjaro store url
  DesktopModules/Vanjaro/UXManager/Library/Base.ascx.cs
Labels: ignore for release

#2072 Updated Vanjaro Store url
  DesktopModules/Vanjaro/UXManager/Library/Base.ascx.cs
Labels: ignore for release

#2071 Not redirect set page of Terms & Privacy on Sign Up block
  DesktopModules/Vanjaro/Core/Extensions/Notification/Notification/Managers/TasksManager.cs
  DesktopModules/Vanjaro/Core/Library/Themes/Basic/blocks/Register/Templates/Default.cshtml
  DesktopModules/Vanjaro/UXManager/Extensions/Block/Register/Entities/Register.cs
Labels: Bug, Area: Backend
