Repository vanjarosoftware/Vanjaro.Platform, pull requests merged in 2022-02, with the labels that each got.

#2080 Reverted background video css changes
  DesktopModules/Vanjaro/UXManager/Library/Resources/Scripts/GrapesJsManagers/css/uxmanager.css
  Portals/_default/Skins/Vanjaro/Resources/css/skin.css
Labels: ignore for release

#2081 Removed z-index css
  Portals/_default/Skins/Vanjaro/Resources/css/skin.css
Labels: ignore for release

#2082 Background not visible in responsive mode
  DesktopModules/Vanjaro/UXManager/Library/Resources/Scripts/GrapesJsManagers/css/uxmanager.css
  Portals/_default/Skins/Vanjaro/Resources/css/skin.css
Labels: ignore for release

#2085 Need page manager ApplyLayout method public inside of internal access modifier to access Vanjaro App
  DesktopModules/Vanjaro/UXManager/Extensions/Menu/Pages/Managers/PagesManager.cs
Labels: Bug, Enhancement, Area: Backend

#2093 Installer not working with verion 1.3.0
  DesktopModules/Vanjaro/Installer/Main.cs
Labels: Bug, Release: Minor, Priority: Low, Area: Backend

#2094 Hybrid mode with Vanjaro Apps showing Persona Bar
  DesktopModules/Vanjaro/UXManager/Extensions/Migrate/Components/HttpModule.cs
Labels: Bug, Applies to: Extension Only, Area: Backend

#2096 Implemented user import feature in vanjaro
  DesktopModules/Vanjaro/Common/Engines/UIEngine/AngularBootstrap/Elements/Import.htm
  DesktopModules/Vanjaro/Common/Frameworks/AngularJS/Plugins/AngularCsvImport/angular-csv-import.js
  DesktopModules/Vanjaro/Common/Frameworks/AngularJS/Plugins/AngularCsvImport/angular-csv-import.min.js
  DesktopModules/Vanjaro/Common/Frameworks/AngularJS/Plugins/mnCommonService/mnCommonService.min.js
  DesktopModules/Vanjaro/Common/Frameworks/AngularJS/Plugins/x-editable/js/xeditable.js
  DesktopModules/Vanjaro/Common/Frameworks/AngularJS/Plugins/x-editable/js/xeditable.min.js
  DesktopModules/Vanjaro/UXManager/Extensions/Menu/Users/Controllers/ImportController.cs
  DesktopModules/Vanjaro/UXManager/Extensions/Menu/Users/Controllers/UIController.cs
  DesktopModules/Vanjaro/UXManager/Extensions/Menu/Users/Entities/Import/ImportField.cs
  DesktopModules/Vanjaro/UXManager/Extensions/Menu/Users/Entities/Import/Job.cs
  DesktopModules/Vanjaro/UXManager/Extensions/Menu/Users/Factories/AppFactory.cs
  DesktopModules/Vanjaro/UXManager/Extensions/Menu/Users/Factories/ImportFactory.cs
  DesktopModules/Vanjaro/UXManager/Extensions/Menu/Users/Managers/ImportManager.cs
  DesktopModules/Vanjaro/UXManager/Extensions/Menu/Users/Resources/Stylesheets/app.css
  DesktopModules/Vanjaro/UXManager/Extensions/Menu/Users/Users.cs
  DesktopModules/Vanjaro/UXManager/Extensions/Menu/Users/Users.csproj
  DesktopModules/Vanjaro/UXManager/Extensions/Menu/Users/Views/App_LocalResources/Shared.resx
  DesktopModules/Vanjaro/UXManager/Extensions/Menu/Users/Views/Setting/App_LocalResources/Import.resx
  DesktopModules/Vanjaro/UXManager/Extensions/Menu/Users/Views/Setting/Import.html
  DesktopModules/Vanjaro/UXManager/Extensions/Menu/Users/Views/Setting/Import.js
  DesktopModules/Vanjaro/UXManager/Extensions/Menu/Users/Views/Setting/Users.html
Labels: Enhancement, Release: Minor, Priority: Medium

#2099 Improve UI User Import
  DesktopModules/Vanjaro/UXManager/Extensions/Menu/Users/Views/Setting/App_LocalResources/Import.resx
  DesktopModules/Vanjaro/UXManager/Extensions/Menu/Users/Views/Setting/Import.html
Labels: Enhancement

#2100 Fixed: Background video doesn't play (iPhone, iPad) on sections
  DesktopModules/Vanjaro/UXManager/Library/Resources/Scripts/Blocks/section.js
Labels: Bug

#2101 Installer not working with version 1.3.0
  DesktopModules/Vanjaro/Installer/Properties/AssemblyInfo.cs
  DesktopModules/Vanjaro/InstallerSetup/InstallerSetup.vdproj
Labels: Bug, Release: Minor, Priority: Low, Area: Backend

#2102 Increment Version 1.3.1
  DesktopModules/Vanjaro/Core/Library/Properties/GlobalAssemblyInfo.cs
  DesktopModules/Vanjaro/Core/Library/Vanjaro.dnn
  DesktopModules/Vanjaro/Core/Library/VanjaroDistribution.dnn
Labels: Applies to: Platform Only, Applies to: Extension Only

#2108 Enable import button for retry to import if got any error message
  DesktopModules/Vanjaro/Common/Manager/NotificationManager.cs
  DesktopModules/Vanjaro/UXManager/Extensions/Menu/Users/Views/Setting/Import.html
  DesktopModules/Vanjaro/UXManager/Extensions/Menu/Users/Views/Setting/Import.js
Labels: Bug, Enhancement, Applies to: Platform Only, Release: Minor, Area: Backend

#2112 Implement Google Analytics
  DesktopModules/Vanjaro/UXManager/Extensions/Menu/GoogleAnalytics/Controllers/SettingController.cs
  DesktopModules/Vanjaro/UXManager/Extensions/Menu/GoogleAnalytics/Views/App_LocalResources/Shared.resx
  DesktopModules/Vanjaro/UXManager/Extensions/Menu/GoogleAnalytics/Views/Setting/App_LocalResources/Setting.resx
  DesktopModules/Vanjaro/UXManager/Extensions/Menu/GoogleAnalytics/Views/Setting/Setting.html
  DesktopModules/Vanjaro/UXManager/Extensions/Menu/GoogleAnalytics/Views/Setting/Setting.js
  Portals/_default/Skins/Vanjaro/Base.ascx.cs
Labels: Enhancement, Applies to: Platform Only, Release: Minor, Priority: Low, Area: Backend

#2115 updated ExtensionStoreURL
  DesktopModules/Vanjaro/UXManager/Library/Base.ascx.cs
Labels: ignore for release

#2116 Can not create or migrate to a Vanjaro page on portals
  Portals/_default/Skins/Vanjaro/Managers/MigrateManager.cs
Labels: Bug, Applies to: Extension Only, Release: Minor, Priority: High, Area: Backend
